title: Company Details
form:
    validation: loose
    fields:

        content:
            type: section
            title: 'Details'
            underline: true
        name:
            type: text
            label: 'Company Name'
            size: medium
            placeholder: 'ACME Corp'

        address1:
            type: textarea
            label: 'Address'
            placeholder: '555 Somestreet,\r\nNewville, TX, 77777'
            size: medium
        address2:
            type: textarea
            label: 'Address'
            placeholder: 'Town, City and Country'
            size: medium

        email:
            type: array
            label: 'Email Addresses'
            placeholder_key: Key
            placeholder_value: Email Address

        phone:
            type: array
            label: 'Phone Numbers'
            placeholder_key: Key
            placeholder_value: Phone Number
        facebook:
            type: text
            label: 'Facebook'
            size: medium
            placeholder: ''
        twitter:
            type: text
            label: 'Twitter'
            size: medium
            placeholder: ''
